FROM node:22-alpine AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build


FROM nginx:alpine
RUN rm /etc/nginx/conf.d/*
COPY nginx/conf.d/default.local.conf /etc/nginx/conf.d/
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
